[package]
name = "county-flags"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "0.15.7"
rand = "0.8.5"
reqwest = { version = "0.11.24", features = ["json"] }
serde = "1.0.197"
serde_json = "1.0.127"
tokio = { version = "1.26.0", features = ["full"] }
tweety-rs = "0.1.2"
